#!/usr/bin/env zsh
echo
echo '[init-shell]'
_start_time=$(date +"%s.%3N")

get-shellcheck() {
  case $OSTYPE in
    linux*)
      case $DIST in
        Ubuntu) sudo apt-get install shellcheck ;;
      esac
      ;;
  esac
}

get-shfmt() {
  case $OSTYPE in
    linux*)
      (
        cd $(mktemp -d)
        go mod init tmp
        go get mvdan.cc/sh/cmd/shfmt
      )
      ;;
  esac
}
if ! type -p shfmt >/dev/null; then get-shfmt; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
