#!/usr/bin/env zsh
echo
echo '=============='
echo 'init-memcached'
echo '=============='
_start_time=$(date +"%s.%3N")

get-memcached() {
  case "${OSTYPE}" in
    darwin*) ;;
    linux*)
      case $DIST_VERSION in
        14.04 | 16.04) ;;
        *) nix-install memcached ;;
      esac
      ;;
  esac
}
if ! type -p memcached >/dev/null; then get-memcached; fi

get-memcached-tool() {
  wget https://raw.githubusercontent.com/memcached/memcached/master/scripts/memcached-tool -O ~/.local/bin/memcached-tool
  chmod +x ~/.local/bin/memcached-tool
}
if ! type -p memcached-tool >/dev/null; then get-memcached-tool; fi

# ----------------------------------------------------------------------
memcached-restart() {
  case "${OSTYPE}" in
    darwin*) ;;
    linux*)
      sudo pkill memcached
      nohup memcached >/dev/null 2>&1 </dev/null &
      ps aux | \grep -G 'memcached.*'
      ;;
  esac
}

memcached-stop() {
  case "${OSTYPE}" in
    darwin*) ;;
    linux*) sudo /usr/bin/pkill memcached ;;
  esac
}

memcached-status() {
  case "${OSTYPE}" in
    darwin*) ;;
    linux*) ps aux | \grep -G 'memcached.*' ;;
  esac
}

# ----------------------------------------------------------------------
get-memcache-top() {
  wget http://memcache-top.googlecode.com/files/memcache-top-v0.6 -O ~/.local/bin/memcache-top
}

# ----------------------------------------------------------------------
alias memcached-monitor='memcached-tool 127.0.0.1:11211 display'
alias memcached-info='memcached-tool 127.0.0.1:11211 stats'
alias memcached-dump='memcached-tool 127.0.0.1:11211 dump'
alias memcache-top='perl memcached-top'
alias mcr="memcached-restart"
alias mcp="memcached-status"
alias mci="memcached-info"
alias mcm="memcached-monitor"
alias mck="memcached-stop"

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
