#!/usr/bin/env zsh
echo
echo '==========='
echo 'init-heroku'
echo '==========='
_start_time=$(date +"%s.%3N")

function get-heroku() {
  case "${OSTYPE}" in
    freebsd* | darwin*) nix-install heroku-3.43.16 ;;
    linux*) curl https://cli-assets.heroku.com/install.sh | sh ;;
  esac
}
if ! type -p heroku >/dev/null; then get-heroku; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
