#!/usr/bin/env zsh
echo
echo '==============='
echo 'init-asdf--util'
echo '==============='
_start_time=$(date +"%s.%3N")

set-asdf-completion() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      source ~/.asdf/completions/asdf.bash
      ;;
  esac
}
if [ -f ~/.asdf/asdf.sh ]; then set-asdf-completion; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
