#!/usr/bin/env zsh

export REQUIRED_NODE_VERSION='10.15.3'
export node='NODE_NO_READLINE=1 node'
case $OSTYPE in msys | cygwin) export PATH=$(get-winpath "C:\Program Files\nodejs"):$PATH ;; esac

# ----------------------------------------------------------------------
# ### version control ###
get-ndenv() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      anyenv install ndenv
      git clone https://github.com/pine/ndenv-yarn-install.git "$(ndenv root)/plugins/ndenv-yarn-install"
      exec -l zsh
      ;;
  esac
}

# ----------------------------------------------------------------------
# ### installation ###
get-node-by-asdf() {
  case "$OSTYPE" in
    msys | cygwin) choco install nodejs ;;
    linux*)
      case $(asdf plugin-list) in *nodejs*) ;; *) asdf plugin-add nodejs ;; esac
      rm -rf ~/.asdf/keyrings/nodejs
      ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
      asdf install nodejs $REQUIRED_NODE_VERSION
      asdf global nodejs $REQUIRED_NODE_VERSION
      ;;
  esac
}

get-node() {
  case "$OSTYPE" in
    msys | cygwin) choco install nodejs ;;
    linux*)
      ndenv install v$REQUIRED_NODE_VERSION
      ndenv rehash
      ndenv global v$REQUIRED_NODE_VERSION
      ;;
      # get-global-npm-packages ;;
  esac
}

set-node-with-ndenv() {
  case "$OSTYPE" in
    linux*) ndenv global v$REQUIRED_NODE_VERSION ;;
  esac
}

# ----------------------------------------------------------------------
# ### NPM ###
get-global-npm-packages() {
  npm install -g \
    http-server \
    node-plantuml \
    npm2dot \
    tern
}
if ! type -p npm >/dev/null; then get-node; fi

get-global-npm-packages-old() {
  npm install -g \
    bower \
    grunt-cli \
    gulp \
    hexo-cli \
    html2jade \
    less \
    phantomjs \
    requirejs \
    yamljs
}

# ----------------------------------------------------------------------
# ReasonML
get-revery() {
  case $OSTYPE in
    linux*)
      case $DIST in
        Ubuntu | Debian)
          sudo apt-get install \
            libpng-dev \
            libbz2-dev \
            m4 \
            xorg-dev \
            libglu1-mesa-dev \
            libharfbuzz-dev \
            libgtk-3-dev
          npm install -g esy
          ;;
      esac
      ;;
  esac
}

# ----------------------------------------------------------------------
# Other
rebuild-sass() {
  npm uninstall --save-dev gulp-sass
  npm install --save-dev gulp-sass@2
  npm rebuild node-sass
}

get-watchman() {
  case $OSTYPE in
    linux*)
      git clone https://github.com/facebook/watchman.git
      cd watchman
      sh ./autogen.sh
      ./configure
      make
      sudo make install
      cd ..
      sudo rm -fr watchman
      ;;
  esac
}
# if ! type -p watchman > /dev/null; then get-watchman; fi

get-yoeman() {
  npm i -g \
    generator-standard-readme \
    yo
}

get-google-chrome() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      case $DIST in
        Debian | Ubuntu)
          sudo apt-get update
          sudo apt-get install -y libappindicator1 fonts-liberation libxss1
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome*.deb
          ;;
      esac
      ;;
  esac
}
