#!/usr/bin/env zsh

export REQUIRED_OCAML_VERSION=4.05.0
export REQUIRED_COQ_VERSION=8.7.2

get-ocaml() {
  case $OS in
    linux*)
      case $DIST in
        Debian* | Ubuntu*)
          case $DIST_VERSION in
            16.04) get-ocaml-by-asdf ;;
            18.04)
              case $REV in
                WSL) get-ocaml-by-ocamlbrew ;;
                *) get-ocaml-by-asdf ;;
              esac
              ;;
          esac
          ;;
      esac
      ;;
  esac
}

get-ocaml-by-asdf() {
  case $(asdf plugin-list) in *ocaml*) ;; *) asdf plugin-add ocaml ;; esac
  asdf install ocaml $REQUIRED_OCAML_VERSION
  asdf global ocaml $REQUIRED_OCAML_VERSION
  (get-global-opam-packages 2 &)
}

get-ocaml-by-ocamlbrew() {
  curl -kL https://raw.github.com/hcarty/ocamlbrew/master/ocamlbrew-install | bash
  source ~/ocamlbrew/ocaml-*/etc/ocamlbrew.bashrc
  opam switch $REQUIRED_OCAML_VERSION
  eval $(opam config env)
  (get-global-opam-packages 2 &)
}

get-global-opam-packages() {
  opam install \
    core_kernel \
    core \
    ounit \
    utop \
    tuareg \
    reason \
    merlin
}

get-global-npm-packages-for-ocaml() {
  npm i -g \
    ocaml-language-server \
    reason-cli@latest-linux
}

if ! type -p ocaml >/dev/null; then get-ocaml; fi

# ----------------------------------------------------------------------
# Coq
get-coq() {
  nix-install coq
}

get-coq-by-asdf() {
  case $(asdf plugin-list) in *coq*) ;; *) asdf plugin-add coq ;; esac
  asdf install coq $REQUIRED_COQ_VERSION
  asdf global coq $REQUIRED_COQ_VERSION
}
