#!/usr/bin/env zsh

export REQUIRED_RUST_VERSION=1.33.0
export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:~/.asdf/installs/rust/$REQUIRED_RUST_VERSION/bin

get-rust() {
  case $OSTYPE in
    linux*)
      asdf plugin-add rust
      asdf install rust $REQUIRED_RUST_VERSION
      asdf global rust $REQUIRED_RUST_VERSION
      get-global-cargo-packages
      ;;
  esac
}

get-global-cargo-packages() {
  cargo install \
    ripgrep \
    fselect
}
if ! type rustc >/dev/null; then get-rust; fi
