#!/usr/bin/env zsh
echo
echo '=========='
echo 'init-shell'
echo '=========='

get-shellcheck() {
  case $OSTYPE in
    linux*)
      case $DIST in
        Ubuntu) sudo apt-get install shellcheck ;;
      esac
      ;;
  esac
}

get-shfmt() {
  case $OSTYPE in
    linux*)
      (
        cd $(mktemp -d)
        go mod init tmp
        go get mvdan.cc/sh/cmd/shfmt
      )
      ;;
  esac
}
if ! type -p shfmt >/dev/null; then get-shfmt; fi
