#!/usr/bin/env zsh
echo
echo '[init-haskell]'
_start_time=$(date +"%s.%3N")

export REQUIRED_GHC_VERSION=8.4.3
# export REQUIRED_CABAL_VERSION=1.22.9.0

get-ghc() {
  case $OSTYPE in
    freebsd* | darwin*) nix-install ghc 2>/dev/null || echo "Warning: nix-install ghc failed, trying alternative methods" ;;
    linux*)
      case $DIST in
        Redhat* | RedHat* | Debian | Ubuntu*)
          nix-install ghc 2>/dev/null || echo "Warning: nix-install ghc failed, trying alternative methods"
          ;;
      esac
      ;;
  esac
}

get-ghc-by-asdf() {
  case $OSTYPE in
    freebsd* | darwin* | linux*)
      case $(asdf plugin list) in *haskell*) ;; *) asdf plugin add haskell ;; esac
      asdf install haskell $REQUIRED_GHC_VERSION
      asdf global haskell $REQUIRED_GHC_VERSION
      ;;
  esac
}

get-cabal() {
  case $OSTYPE in
    freebsd* | darwin*)
      nix-install cabal-install 2>/dev/null || echo "Warning: nix-install cabal-install failed, trying alternative methods"
      cabal update 2>/dev/null || true
      ;;
    linux*)
      case $DIST in
        Redhat* | RedHat* | Debian | Ubuntu*)
          nix-install cabal-install 2>/dev/null || echo "Warning: nix-install cabal-install failed, trying alternative methods"
          cabal update 2>/dev/null || true
          ;;
      esac
      ;;
  esac
}

get-stack() {
  curl -sSL https://get.haskellstack.org/ | sh
}

if ! type -p ghc >/dev/null; then get-ghc && get-cabal; fi
if ! type -p cabal >/dev/null; then get-cabal; fi
if ! type -p stack >/dev/null; then get-stack; fi

get-global-cabal-packages() {
  cabal install stack
  cabal install hasktags
}

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
