#!/usr/bin/env zsh
echo
echo '[init-postgresql]'
_start_time=$(date +"%s.%3N")

export REQUIRED_POSTGRESQL_VERSION=9.2.15
export PSQL_PAGER='less -S'

# ----------------------------------------------------------------------
# ### installation ###
get-postgresql() {
  case "${OSTYPE}" in
    darwin* | linux*)
      case "${DIST}" in
        Redhat | RedHat)
          sudo yum install postgresql-server postgresql-devel postgresql-contrib
          set-postgresql
          ;;
      esac
      ;;
  esac
}

set-postgresql() {
  case "${OSTYPE}" in
    darwin* | linux*)
      case "${DIST}" in
        Redhat | RedHat)
          sudo postgresql-setup initdb
          sudo sed -i "s|^\(host   allow            allow            127.0.0.1/32           \)ident|\1md5|g" /var/lib/pgsql/data/pg_hba.conf
          sudo sed -i "s|^\(host   allow            allow            ::1/128                \)ident|\1md5|g" /var/lib/pgsql/data/pg_hba.conf
          sudo chkconfig postgresql on
          ;;
      esac
      ;;
  esac
}
if ! type -p psql >/dev/null; then get-postgresql; fi

# ----------------------------------------------------------------------
pg-restart() {
  case "${OSTYPE}" in
    darwin*)
      sudo service postgresql stop
      sudo service postgresql start
      sudo service postgresql status
      ;;
    linux*)
      case "${DIST}" in
        Redhat | RedHat)
          sudo service postgresql stop
          sudo service postgresql start
          sudo service postgresql status
          ;;
        Debian | Ubuntu)
          parts restart postgresql
          parts status postgresql
          ;;
      esac
      ;;
  esac
}

pg-stop() {
  case "${OSTYPE}" in
    darwin*) sudo service postgresql stop ;;
    linux*)
      case "${DIST}" in
        Redhat | RedHat) sudo service postgresql stop ;;
        Debian | Ubuntu) parts stop postgresql ;;
      esac
      ;;
  esac
}

pg-status() {
  case "${OSTYPE}" in
    darwin*) sudo service postgresql status ;;
    linux*)
      case "${DIST}" in
        Redhat | RedHat) sudo service postgresql status ;;
        Debian | Ubuntu) parts status postgresql ;;
      esac
      ;;
  esac
}

alias pgr="pg-restart"
alias pgp="ps aux | grep [p]ostgres"
alias pgs="pg-status"
alias pgt="pg-stop"
alias pgk="pg-stop"
# alias psql='rlwrap -a -pCYAN -if ~/.local/rlwrap/sqlplus psql'

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
