#!/usr/bin/env zsh
echo
echo '[init-llm]'
_start_time=$(date +"%s.%3N")

# ----------------------------------------------------------------------
# ### claude ###
# FOR USERS USING SCREEN ON UBUNTU, ADD THE FOLLOWING CODE TO /etc/sudoers:
# # Temporary workaround for Claude Code, which attempts to run
# # `sudo mkdir -p /run/screen` during startup or execution.
# # This prevents repeated password prompts.
# app ALL=(ALL) NOPASSWD: /usr/bin/mkdir -p /run/screen
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1

get-claude() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      npm install -g @anthropic-ai/claude-code
      exec -l zsh
      ;;
  esac
}
if ! type -p claude >/dev/null; then get-claude; fi

# ----------------------------------------------------------------------
# ### Q CLI ###
get-qcli() {
  case "${OSTYPE}" in
    linux*)
      case "${DIST}" in
        Ubuntu)
          wget https://desktop-release.q.us-east-1.amazonaws.com/latest/amazon-q.deb
          sudo apt-get install -f
          sudo dpkg -i amazon-q.deb
          ;;
      esac
      ;;
  esac
}
if ! type -p q >/dev/null; then get-qcli; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
