#!/usr/bin/env zsh

update-ubuntu-from-12.04-to-14.04() {
  case $OSTYPE in
    linux*)
      case "${DIST}" in
        Ubuntu)
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get dist-upgrade
          sudo apt-get install update-manager-core
          sudo do-release-upgrade
          ;;
      esac
      ;;
  esac
}
