#!/usr/bin/env zsh
echo
echo '[init-chocolatey]'
_start_time=$(date +"%s.%3N")

# Chocolatey
case $OSTYPE in
  msys | cygwin)
    export PATH=/c/ProgramData/Chocolatey/bin:$PATH

    get-choco() {
      cmd /c @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%
      %ALLUSERSPROFILE%\chocolatey\bin
      # set ChocolateyPath C:\ProgramData\chocolatey\lib
    }

    if ! type -p choco >/dev/null; then get-choco; fi
    ;;
esac

# ----------------------------------------------------------------------
# Packman
case $OSTYPE in
  msys)
    get-pacman() {
      choco install msys2
      # pacman -Sy pacman
      # pacman -Syu
      # pacman -S zsh
    }

    get-base-pacman-packages() {
      pacman -S conemu git tar unzip make patch
      pacman -S mingw-w64-x86_64-toolchain
      # set ConEmuDir c:\tools\msys64\opt\bin
      # set ConEmuWorkDir %USERPROFILE\OneDrive
    }

    if ! type -p pacman >/dev/null; then get-pacman && get-global-pacman-packages; fi
    ;;
esac

# ----------------------------------------------------------------------
# AptCyg
case $OSTYPE in
  cygwin)
    get-aptcyg() {
      choco install cygwin
      wget https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg -O /usr/local/bin/apt-cyg
      chmod 755 /usr/local/bin/apt-cyg
    }

    get-base-aptcyg-packages() {
      apt-cyg install \
        base-cygwin \
        base-files \
        bash \
        binutils \
        cron \
        ctags \
        curl \
        cygrunsrv \
        cygutils \
        cygwin \
        cygwin-devel \
        findutils \
        gawk \
        gcc-core \
        gcc-g++ \
        git \
        gnuplot \
        grep \
        hostname \
        info \
        less \
        libbz2-devel \
        libcrypt-devel \
        libcurl-devel \
        liblzma-devel \
        libsqlite3-devel \
        make \
        mintty \
        openssh \
        openssl-devel \
        patch \
        perl-DBD-SQLite \
        perl-WWW-Curl \
        ping \
        pkg-config \
        renameutils \
        rsync \
        run \
        screen \
        sed \
        shutdown \
        tar \
        tree \
        unzip \
        util-linux \
        vim \
        wget \
        which \
        whois \
        zip \
        zoo \
        zsh
    }

    if ! apt-cyg >/dev/null; then get-aptcyg && get-base-aptcyg-packages; fi
    ;;
esac

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
