#!/usr/bin/env zsh
echo
echo '[init-edit]'
_start_time=$(date +"%s.%3N")

# Edit
export REQUIRED_EDIT_VERSION=1.0.0

# ----------------------------------------------------------------------
# ### installation ###
get-edit() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      wget https://github.com/microsoft/edit/releases/download/v1.0.0/edit-${REQUIRED_EDIT_VERSION}-x86_64-linux-gnu.xz
      unxz edit-${REQUIRED_EDIT_VERSION}-x86_64-linux-gnu.xz
      chmod +x edit-${REQUIRED_EDIT_VERSION}-x86_64-linux-gnu
      mv edit-${REQUIRED_EDIT_VERSION}-x86_64-linux-gnu ~/.local/bin/edit
      ;;
  esac
}
if ! type edit >/dev/null; then get-edit; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
