#!/usr/bin/env zsh

get-shellcheck() {
  case $OSTYPE in
    linux*)
      case $DIST in
        Ubuntu) sudo apt-get install shellcheck ;;
      esac
      ;;
  esac
}

get-shfmt() {
  case $OSTYPE in
    linux*)
      local current_pwd=$(pwd)
      cd $(mktemp -d)
      go mod init tmp
      go get mvdan.cc/sh/cmd/shfmt
      cd $current_pwd
      ;;
  esac
}
