#!/usr/bin/env zsh

upgrade-rbenv-by-ruby-build() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      rm -fr "$(rbenv root)"/plugins/ruby-build
      git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
      ;;
  esac
}
