#!/usr/bin/env zsh
echo
echo '[init-os-update]'
_start_time=$(date +"%s.%3N")

update-ubuntu-from-12.04-to-14.04() {
  case $OSTYPE in
    linux*)
      case "${DIST}" in
        Ubuntu)
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get dist-upgrade
          sudo apt-get install update-manager-core
          sudo do-release-upgrade
          ;;
      esac
      ;;
  esac
}

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
