#!/usr/bin/env zsh

terraform-remote-config() {
  terraform remote config -backend=S3 -backend-config="bucket=tfstate.d" -backend-config="key=$1.tfstate"
  terraform remote push
}

alias tfrc="terraform-remote-config"
alias tfr="terraform remote"
alias tfs="terraform show"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfd="terraform destroy"
