#!/usr/bin/env zsh
echo
echo '========'
echo 'init-csv'
echo '========'
_start_time=$(date +"%s.%3N")

# ----------------------------------------------------------------------
# ### installation ###
get-trdsql() {
  case "${OSTYPE}" in
    darwin*) brew install noborus/tap/trdsql ;;
    linux*) brew install noborus/tap/trdsql ;;
  esac
}
if ! type -p trdsql >/dev/null; then get-trdsql; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
