#!/usr/bin/env zsh

export REQUIRED_TERRAFORM_VERSION=0.14.6
export REQUIRED_TERRAFORM_SWITCHER_VERSION=0.7.737
export PATH=~/.$PATH

get-tfenv() {
  anyenv install tfenv
}
if ! type -p tfenv >/dev/null; then get-tfenv; fi

get-terraform-switcher() {
  (
    cd ~/.local/bin
    rm -fr terraform*
    case "${OSTYPE}" in
      linux*)
        wget https://github.com/warrensbox/terraform-switcher/releases/download/${REQUIRED_TERRAFORM_SWITCHER_VERSION}/terraform-switcher_${REQUIRED_TERRAFORM_SWITCHER_VERSION}_linux_amd64.tar.gz
        tar zxvf terraform-switcher_${REQUIRED_TERRAFORM_SWITCHER_VERSION}_linux_amd64.tar.gz
        ;;
    esac
  )
}

set-terraform-switcher() {
  local tfswitchrc_path=".tfswitchrc"
  if [ -f "$tfswitchrc_path" ]; then
    if [ -f ~/.local/bin/terraform ]; then rm ~/.local/bin/terraform; fi
    tfswitch -b ~/.local/bin/terraform $REQUIRED_TERRAFORM_VERSION
  fi
}
# if type -p tfswitch >/dev/null; then
#   # @todo
#   # add-zsh-hook chpwd set-terraform-switcher
#   set-terraform-switcher
# fi

get-terraform() {
  tfenv install $REQUIRED_TERRAFORM_VERSION
  # tfswitch -b ~/.local/bin/terraform $REQUIRED_TERRAFORM_VERSION
  # echo $REQUIRED_TERRAFORM_VERSION >~/.tfswitchrc
}
if ! type -p terraform >/dev/null; then get-terraform; fi

get-terraform-by-tfswitch() {
  tfswitch -b ~/.local/bin/terraform $REQUIRED_TERRAFORM_VERSION
  echo $REQUIRED_TERRAFORM_VERSION >~/.tfswitchrc
}

alias tf="terraform"
alias tfi="terraform init"
alias tfs="terraform show"
alias tfp="terraform plan"
alias tfv="terraform validate"
alias tfa="terraform apply"
alias tfd="terraform destroy"
