#!/usr/bin/env zsh
echo
echo '[init-packer]'
_start_time=$(date +"%s.%3N")

export REQUIRED_PACKER_VERSION=1.7.2

get-packer() {
  wget https://releases.hashicorp.com/packer/${REQUIRED_PACKER_VERSION}/packer_${REQUIRED_PACKER_VERSION}_linux_amd64.zip
  unzip packer_${REQUIRED_PACKER_VERSION}_linux_amd64.zip -d ~/.local/bin/
  rm -f packer_${REQUIRED_PACKER_VERSION}_linux_amd64.zip
}
if ! type -p packer >/dev/null; then get-packer; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
