#!/usr/bin/env zsh
echo
echo '[init-crystal]'
_start_time=$(date +"%s.%3N")

export REQUIRED_CRYSTAL_VERSION=0.25.0

get-crystal() {
  case $OSTYPE in
    linux*)
      case $(asdf plugin list) in *crystal*) ;; *) asdf plugin add crystal ;; esac
      asdf install crystal $REQUIRED_CRYSTAL_VERSION
      asdf set crystal $REQUIRED_CRYSTAL_VERSION
      ;;
  esac
}

if ! type -p asdf exec crystal version >/dev/null; then get-crystal; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
