#!/usr/bin/env zsh
echo
echo '==============='
echo 'init-asdf--util'
echo '==============='

set-asdf-completion() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      source ~/.asdf/completions/asdf.bash
      ;;
  esac
}
if [ -f ~/.asdf/asdf.sh ]; then set-asdf-completion; fi
