#!/usr/bin/env zsh

export REQUIRED_TERRAFORM_VERSION=0.11.14
export REQUIRED_TERRAFORM_SWITCHER_VERSION=0.7.737
export PATH=~/.$PATH

get-terraform-switcher() {
  (
    cd ~/.local/bin
    rm -fr terraform*
    case "${OSTYPE}" in
      linux*)
        wget https://github.com/warrensbox/terraform-switcher/releases/download/${REQUIRED_TERRAFORM_SWITCHER_VERSION}/terraform-switcher_${REQUIRED_TERRAFORM_SWITCHER_VERSION}_linux_amd64.tar.gz
        tar zxvf terraform-switcher_${REQUIRED_TERRAFORM_SWITCHER_VERSION}_linux_amd64.tar.gz
        ;;
    esac
  )
}
if ! type -p tfswitch >/dev/null; then get-terraform-switcher; fi

get-terraform() {
  tfswitch -b ~/.local/bin/terraform $REQUIRED_TERRAFORM_VERSION
  echo $REQUIRED_TERRAFORM_VERSION >~/.tfswitchrc
}
if ! type -p terraform >/dev/null; then get-terraform; fi
