#!/usr/bin/env zsh

export REQUIRED_PHP_VERSION=7.2.7

# ### version control ###
get-phpenv() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*) anyenv install phpenv && exec -l zsh ;;
  esac
}

# ----------------------------------------------------------------------
# ### installation ###
get-php() {
  case "${OSTYPE}" in
    freebsd* | darwin*) nix-install php ;;
    linux*)
      case $DIST_VERSION in
        14.04) sudo apt-get install php-$REQUIRED_PHP_VERSION ;;
        16.04 | 18.04) sudo apt install php ;;
        *) nix-install php ;;
      esac
      ;;
  esac
}
if ! type -p php >/dev/null; then get-php; fi
