#!/usr/bin/env zsh
echo
echo '[init-slack]'
_start_time=$(date +"%s.%3N")

get-slackchat() {
  case "${OSTYPE}" in
    darwin* | linux*)
      wget https://github.com/vektorlab/slackcat/releases/download/v0.7/slackcat-0.7-linux-amd64 -O ~/.local/bin/slackchat
      chmod +x ~/.local/bin/slackchat
      ;;
  esac
}

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
