#!/usr/bin/env zsh
echo
echo '============='
echo 'init-homebrew'
echo '============='
_start_time=$(date +"%s.%3N")

get-brew() {
  case "${OSTYPE}" in
    darwin*) ;;
    linux*)
      git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
      mkdir ~/.linuxbrew/bin
      ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
      eval $(~/.linuxbrew/bin/brew shellenv)
      brew vendor-install ruby
      ;;
  esac
}

get-base-brew-packages() {
  case "${OSTYPE}" in
    darwin*)
      brew install \
        jq \
        memcached \
        the_silver_searcher \
        tree
      ;;
    linux*)
      case "${DIST}" in
        Redhat | RedHat)
          brew install homebrew/dupes/gperf
          ;;
        Debian | Ubuntu)
          brew install \
            aws-vault \
            ghq \
            hadolint \
            jq \
            peco \
            ripgrep
          ;;
      esac
      ;;
  esac
}

case "${OSTYPE}" in
  darwin*) ;;
  linux*)
    case $DIST in
      RedHat | Redhat | Debian)
        if [ -d ~/.linuxbrew ]; then eval $(~/.linuxbrew/bin/brew shellenv); fi
        ;;
      Ubuntu)
        case $DIST_VERSION in
          16.04 | 18.04 | 20.04)
            if [ -d ~/.linuxbrew ]; then eval $(~/.linuxbrew/bin/brew shellenv); fi
            ;;
        esac
        ;;
    esac
    ;;
esac
if ! type -p brew >/dev/null; then get-brew && get-base-brew-packages; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
