#!/usr/bin/env zsh
echo
echo '[init-jobcan]'
_start_time=$(date +"%s.%3N")

get-jobcan() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      (
        wget https://github.com/amiyzku/jobcan-cli/releases/download/v0.1.1/jobcan-x86_64-unknown-linux-gnu.tar.gz
        tar -xvzf jobcan-x86_64-unknown-linux-gnu.tar.gz
        mv jobcan ~/.local/bin/
        rm jobcan-x86_64-unknown-linux-gnu.tar.gz
      )
      ;;
  esac
}
if ! type -p jobcan >/dev/null; then get-jobcan; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
