#!/usr/bin/env zsh
echo
echo '[init-docker]'
_start_time=$(date +"%s.%3N")

get-docker() {
  case "${OSTYPE}" in
    msys | cygwin) choco install boot2docker ;;
    freebsd* | darwin*) ;;
    linux*)
      case "${DIST}" in
        Redhat | RedHat)
          sudo yum update
          sudo yum install -y yum-util
          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          sudo yum-config-manager --disable docker-ce-edge
          sudo yum makecache fast
          sudo yum install -y docker-ce
          local current_user_name=$(whoami)
          sudo usermod -aG docker ${current_user_name}
          ;;
        Debian)
          sudo apt-get update
          sudo apt-get install -y docker.io
          local current_user_name=$(whoami)
          sudo usermod -aG docker ${current_user_name}
          ;;
        Ubuntu)
          case $DIST_VERSION in
            12.04 | 14.04)
              sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
              if [ -f /etc/apt/sources.list.d/docker.list ]; then
                sudo rm /etc/apt/sources.list.d/docker.list
                sudo touch /etc/apt/sources.list.d/docker.list
              fi
              case "${DIST_VERSION}" in
                12.04) sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" >> /etc/apt/sources.list.d/docker.list' ;;
                14.04) sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list' ;;
              esac
              sudo apt-get update
              sudo apt-get purge lxc-docker*
              sudo apt-cache policy docker-engine
              sudo apt-get update
              sudo apt-get install -y docker-engine
              local current_user_name=$(whoami)
              sudo usermod -aG docker ${current_user_name}
              ;;
            16.04)
              sudo apt install docker
              ;;
            18.04 | 20.04 | 22.04 | 24.04)
              sudo apt-get update
              sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test edge"
              sudo apt-get update
              sudo apt-get install docker-ce docker-ce-cli containerd.io
              ;;
          esac
          ;;
      esac
      ;;
  esac
}
case $OSTYPE in linux) if ! type -p docker >/dev/null; then get-docker; fi ;; esac

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
