#!/usr/bin/env zsh
echo
echo '========================'
echo 'init-amazon-web-services'
echo '========================'

export SAM_CLI_TELEMETRY=0

get-aws() {
  if ! type -p pip >/dev/null; then get-pip; fi
  case "${OSTYPE}" in
    freebsd*) ;;
    darwin* | linux*)
      (
        cd ~
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        rm -fr awscliv2.zip
      )
      case "${DIST}" in
        RedHat | redhat)
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
          sudo yum install -y session-manager-plugin.rpm
          ;;
        Ubuntu)
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb
          ;;
      esac
      ;;
  esac
}
if ! type -p aws >/dev/null; then get-aws; fi

get-awslogs() {
  if ! type -p pip >/dev/null; then get-pip; fi
  case "${OSTYPE}" in
    freebsd*) ;;
    darwin* | linux*)
      pip install -U awslogs
      ;;
  esac
}
if ! type -p awslogs >/dev/null; then get-awslogs; fi

get-ecs-cli() {
  if ! type -p pip >/dev/null; then get-pip; fi
  case "${OSTYPE}" in
    freebsd*) ;;
    darwin*)
      sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-darwin-amd64-latest
      ;;
    linux*)
      sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
      ;;
  esac
}
# if ! type -p ecs-cli >/dev/null; then get-ecs-cli; fi

get-aws2-wrap() {
  pip3 install aws2-wrap==1.1.9
}
if ! type -p aws2-wrap >/dev/null; then get-aws2-wrap; fi

get-aws-cdk() {
  npm i -g aws-cdk
}
if ! type -p cdk >/dev/null; then get-aws-cdk; fi

get-aws-sam() {
  case "${OSTYPE}" in
    darwin* | linux*)
      brew tap aws/tap
      brew install aws-sam-cli
      ;;
  esac
}
# if ! type -p sam >/dev/null; then get-aws-sam; fi

get-aws-rails-provisioner() {
  case "${OSTYPE}" in
    linux*)
      case "${DIST}" in
        Ubuntu) sudo apt install gnupg2 pass ;;
      esac
      ;;
  esac
  gem install aws-rails-provisioner --pre
}
if ! type -p aws-rails-provisioner >/dev/null; then get-aws-rails-provisioner; fi

fix-compdef-problem() {
  touch ~/.zshenv
  echo 'autoload -Uz compinit
compinit' >>~/.zshenv
}
