#!/usr/bin/env zsh
echo
echo '[init-red]'
_start_time=$(date +"%s.%3N")

export REQUIRED_RED_VERSION=064

get-red() {
  case $OSTYPE in
    linux*)
      case $DIST in
        Ubuntu | Debian)
          sudo apt-get install lib32ncurses5 lib32z1 libc6-i386 libcurl3
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libc6:i386 libcurl3:i386
          wget https://static.red-lang.org/dl/linux/red-${REQUIRED_RED_VERSION} -O ~/.local/bin/red-${REQUIRED_RED_VERSION}
          chmod 755 ~/.local/bin/red-${REQUIRED_RED_VERSION}
          ln -s ~/.local/bin/red-${REQUIRED_RED_VERSION} ~/.local/bin/red
          ;;
      esac
      ;;
  esac
}

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
