#!/usr/bin/env zsh

# Wercker
export WERCKER_ENVIRONMENT_FILE=./.env

get-wercker() {
  curl -L https://s3.amazonaws.com/downloads.wercker.com/cli/stable/linux_amd64/wercker -o ~/.local/bin/wercker
  chmod u+x ~/.local/bin/wercker
}
if ! type -p wercker >/dev/null; then get-wercker; fi
