#!/usr/bin/env zsh

get-aws() {
  if ! type -p pip >/dev/null; then get-pip; fi
  case "${OSTYPE}" in
    freebsd*) ;;
    darwin* | linux*)
      pip install -U awscli s3cmd
      fix-compdef-problem
      ;;
  esac
}
if ! type -p aws >/dev/null; then get-aws; fi

get-aws-cdk() {
  npm i -g aws-cdk
}
if ! type -p cdk >/dev/null; then get-aws-cdk; fi

fix-compdef-problem() {
  touch ~/.zshenv
  echo 'autoload -Uz compinit
compinit' >>~/.zshenv
}
