#!/usr/bin/env zsh

# export EDITOR=/usr/local/bin/vi
# export LANG=ja_JP.UTF-8
# export LANG=ja_JP.eucJP
export CLICOLOR=1
export EDITOR='emacsclient -t' # vim -f
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=UTF-8
export LC_MESSAGES=C
export MAILPATH=$HOME/MailBox/postmaster/maildir
export PATH=/usr/sbin:/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/bin:$HOME/local/bin:$PATH
export PATH="/opt/local/bin:$PATH"
export PATH="/opt/local/sbin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$(parse_git_branch)\$ "

get-ntp() {
  case "${OSTYPE}" in
    linux*)
      case "${DIST}" in
        Redhat | RedHat) sudo yum install -y ntp ;;
        Debian | Ubuntu) sudo apt-get install -y ntp ;;
      esac
      ;;
  esac
}

set-ntp() {
  case "${OSTYPE}" in
    linux*)
      case "${DIST}" in
        Redhat | RedHat)
          sudo chkconfig ntpd on
          sudo service ntpd start
          ;;
        Debian)
          sudo service ntp stop
          sudo ntpdate ntp.ubuntu.com
          sudo service ntp start
          ;;
        Ubuntu)
          case $DIST_VERSION in
            12.04 | 14.04)
              sudo service ntp stop
              sudo ntpdate ntp.ubuntu.com
              sudo service ntp start
              ;;
            16.04 | 18.04)
              sudo service ntp stop
              sudo service ntp start
              ;;
          esac
          ;;
      esac
      ;;
  esac
}

set-locale() {
  case "${OSTYPE}" in
    linux*)
      case "${DIST}" in
        Redhat | RedHat)
          sudo mv /etc/localtime{,.org}
          sudo ln -s /usr/share/zoneinfo/Japan /etc/localtime
          ;;
        Debian | Ubuntu)
          sudo mv /etc/localtime{,.org}
          sudo ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
          ;;
      esac
      ;;
  esac
}

if [ ! -d ~/.local/bin ]; then mkdir -p ~/.local/bin; fi
