#!/usr/bin/env zsh
echo
echo '[init-asdf]'
_start_time=$(date +"%s.%3N")

get-asdf() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      git clone https://github.com/asdf-vm/asdf.git ~/.asdf
      get-global-asdf-packages
      ;;
  esac
}

set-asdf() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      source ~/.asdf/asdf.sh
      ;;
  esac
}
if [ ! -f ~/.asdf/asdf.sh ] >/dev/null; then get-asdf; fi
if [ -f ~/.asdf/asdf.sh ]; then set-asdf; fi

get-global-asdf-packages() {
  # asdf plugin-add coq
  asdf plugin-add crystal
  asdf plugin-add dotnet-core
  asdf plugin-add elixir
  asdf plugin-add erlang
  asdf plugin-add golang
  # asdf plugin-add haskell
  asdf plugin-add java
  asdf plugin-add nodejs
  asdf plugin-add ocaml
  # asdf plugin-add php
  # asdf plugin-add python
  asdf plugin-add r
  asdf plugin-add rebar
  asdf plugin-add ruby
  asdf plugin-add rust
  # other
  asdf plugin-add helm
  asdf plugin-add kops
  asdf plugin-add kubectl
  asdf plugin-add minikube
  asdf reshim
}

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
