#!/usr/bin/env zsh
echo
echo '============'
echo 'init-ansible'
echo '============'
_start_time=$(date +"%s.%3N")

get-ansible() {
  pip install \
    ansible \
    apache-libcloud
  mkdir -p ~/.gcp
}
if ! type -p ansible-playbook >/dev/null; then get-ansible; fi

# ----------------------------------------------------------------------
# ### ans (ansible wrapper) ###
get-ans() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      git clone https://github.com/nabinno/ans ~/.ans
      eval "$(ans init -)"
      ;;
  esac
}
if ! type -p ans >/dev/null; then get-ans; fi
if type -p ans >/dev/null; then eval "$(ans init -)"; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
