#!/usr/bin/env zsh
echo
echo '==========='
echo 'init-anyenv'
echo '==========='
_start_time=$(date +"%s.%3N")

export PATH="$HOME/.anyenv/bin:$PATH"
export PATH="$HOME/.anyenv/envs/goenv/bin:$PATH"
export PATH="$HOME/.anyenv/envs/nodenv/bin:$PATH"
export PATH="$HOME/.anyenv/envs/plenv/bin:$PATH"
export PATH="$HOME/.anyenv/envs/pyenv/bin:$PATH"
export PATH="$HOME/.anyenv/envs/rbenv/bin:$PATH"

get-anyenv() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      git clone https://github.com/riywo/anyenv ~/.anyenv
      anyenv install --init
      eval "$(anyenv init - zsh)"
      ;;
  esac
}

if ! type -p anyenv >/dev/null; then get-anyenv; fi
if type -p anyenv >/dev/null; then eval "$(anyenv init - zsh)"; fi

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
