#!/usr/bin/env zsh

function get-heroku() {
  case "${OSTYPE}" in
    freebsd* | darwin*) nix-install heroku-3.43.16 ;;
    linux*) curl https://cli-assets.heroku.com/install.sh | sh ;;
  esac
}
if ! type -p heroku >/dev/null; then get-heroku; fi
