#!/usr/bin/env zsh

export REQUIRED_GO_VERSION=1.12.1
export GOPATH=~/.ghq.d

# ### version control ###
get-goenv() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*) anyenv install goenv && exec -l zsh ;;
  esac
}
if ! type -p goenv >/dev/null; then get-goenv; fi

# ----------------------------------------------------------------------
get-go() {
  get-go-by-goenv
}

get-go-by-asdf() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      case $(asdf plugin-list) in *golang*) ;; *) asdf plugin-add golang ;; esac
      asdf install golang $REQUIRED_GO_VERSION
      asdf global golang $REQUIRED_GO_VERSION
      ;;
  esac
}

get-go-by-goenv() {
  case "${OSTYPE}" in
    freebsd* | darwin*) ;;
    linux*)
      if ! type -p goenv >/dev/null; then get-goenv; fi
      goenv install $REQUIRED_GO_VERSION
      set-go
      ;;
  esac
}

set-go() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      goenv global $REQUIRED_GO_VERSION >/dev/null
      export GOROOT=$(go env GOROOT)
      export PATH="$GOROOT/bin:$PATH"
      ;;
  esac
}

if ! type -p go >/dev/null; then
  get-go
  (get-global-go-packages 2 &)
else
  export GOROOT=$(go env GOROOT)
  export PATH="$GOROOT/bin:$PATH"
fi

# ----------------------------------------------------------------------
get-global-go-packages() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      go get -u golang.org/x/tools/cmd/gopls
      go get -u golang.org/x/tools/cmd/goimports
      go get -u golang.org/x/tools/cmd/guru
      go get -u github.com/golang/dep/cmd/dep

      # test
      go get -u github.com/onsi/ginkgo/ginkgo
      go get -u github.com/onsi/gomega

      # debug
      go get -u github.com/go-delve/delve/cmd/dlv
      go get -u github.com/d4l3k/go-pry
      go install -i github.com/d4l3k/go-pry

      # utility
      go get -u github.com/github/hub
      go get -u github.com/peco/peco/cmd/peco
      go get -u github.com/mattn/qq/cmd/qq
      go get -u github.com/mattn/git-fixauthor
      go get -u github.com/shenwei356/csvtk/csvtk
      go get -u github.com/motemen/ghq
      go get -u github.com/k0kubun/pp
      GO111MODULE=off go get -u github.com/motemen/gore/cmd/gore # REPL
      go get -u github.com/rogpeppe/godef                        # 関数定義等の参照パッケージ
      go get -u github.com/nsf/gocode                            # 補完パッケージ
      go get -u golang.org/x/lint/golint                         # flycheckでシンタックスエラーを検知
      go get -u github.com/kisielk/errcheck                      # flycheckでシンタックスエラーを検知
      ;;
  esac
}
