#!/usr/bin/env zsh
echo
echo '[init-ruby--util]'
_start_time=$(date +"%s.%3N")

upgrade-rbenv-by-ruby-build() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      rm -fr "$(rbenv root)"/plugins/ruby-build
      git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
      ;;
  esac
}

_end_time=$(date +"%s.%3N")
echo time: $(echo "$_end_time - $_start_time" | bc) sec
