#!/usr/bin/env zsh

export REQUIRED_RUBY_VERSION=2.5.3
export RUBY_PACKAGE_MANAGER=anyenv

# ### version control ###
get-rbenv() {
  case "${OSTYPE}" in
    freebsd* | darwin* | linux*)
      anyenv install rbenv
      git clone https://github.com/amatsuda/gem-src.git "$(rbenv root)"/plugins/gem-src
      exec -l zsh
      ;;
  esac
}

# ----------------------------------------------------------------------
# ### installation ###
get-ruby() {
  eval "get-ruby-by-${RUBY_PACKAGE_MANAGER}"
  (get-global-gem-packages 2 &)
}

get-ruby-by-asdf() {
  case "${OSTYPE}" in
    cygwin) apt-cyg install ruby ;;
    freebsd* | darwin* | linux*)
      case $(asdf plugin-list) in *ruby*) ;; *) asdf plugin-add ruby ;; esac
      asfd install ruby $REQUIRED_RUBY_VERSION
      asdf global ruby $REQUIRED_RUBY_VERSION
      ;;
  esac
}

get-ruby-by-anyenv() {
  case "${OSTYPE}" in
    cygwin) apt-cyg install ruby ;;
    freebsd* | darwin* | linux*)
      if ! type -p rbenv >/dev/null; then get-rbenv; fi
      rbenv install $REQUIRED_RUBY_VERSION
      rbenv rehash
      rbenv global $REQUIRED_RUBY_VERSION
      ;;
  esac
}

get-global-gem-packages() {
  gem install \
    benchmark-ips \
    bundler \
    compass \
    git-trend \
    haml \
    html2slim \
    peek-rblineprof \
    rack-lineprof \
    rails \
    rblineprof \
    rubygems-bundler \
    serverspec \
    sidekiq \
    slim \
    stackprof \
    unicorn
  gem install rufo -v 0.1.0
}

case ${RUBY_PACKAGE_MANAGER} in
  rbenv)
    if (
      ! type -p ruby >/dev/null &&
        [[ $(rbenv versions | awk '{print $1$2}') == "*system" ]]
    ); then
      get-ruby
    fi
    ;;
esac
